// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SmartWatch_ui

#ifndef _UI_COMP_COLONLABEL_H
#define _UI_COMP_COLONLABEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT colonLabel
#define UI_COMP_COLONLABEL_COLONLABEL 0
#define _UI_COMP_COLONLABEL_NUM 1
lv_obj_t * ui_colonLabel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
