// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SmartWatch_ui

#include "ui_themes.h"

const ui_theme_variable_t _ui_theme_color_deep_space[2] = {0x23192D, 0x23192D};
const ui_theme_variable_t _ui_theme_alpha_deep_space[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_electric_rose[2] = {0xFD0A54, 0xFD0A54};
const ui_theme_variable_t _ui_theme_alpha_electric_rose[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_soft_coral[2] = {0xF57576, 0xF57576};
const ui_theme_variable_t _ui_theme_alpha_soft_coral[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_sunset_glow[2] = {0xFEBF97, 0xFEBF97};
const ui_theme_variable_t _ui_theme_alpha_sunset_glow[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_pale_spring[2] = {0xF5ECB7, 0xF5ECB7};
const ui_theme_variable_t _ui_theme_alpha_pale_spring[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_VIBRANT_SUNSET;

