// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SmartWatch_ui

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#include "ui_theme_manager.h"

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_DEEP_SPACE 0
#define UI_THEME_COLOR_ELECTRIC_ROSE 1
#define UI_THEME_COLOR_SOFT_CORAL 2
#define UI_THEME_COLOR_SUNSET_GLOW 3
#define UI_THEME_COLOR_PALE_SPRING 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_VIBRANT_SUNSET 1

extern const ui_theme_variable_t _ui_theme_color_deep_space[2];
extern const ui_theme_variable_t _ui_theme_alpha_deep_space[2];

extern const ui_theme_variable_t _ui_theme_color_electric_rose[2];
extern const ui_theme_variable_t _ui_theme_alpha_electric_rose[2];

extern const ui_theme_variable_t _ui_theme_color_soft_coral[2];
extern const ui_theme_variable_t _ui_theme_alpha_soft_coral[2];

extern const ui_theme_variable_t _ui_theme_color_sunset_glow[2];
extern const ui_theme_variable_t _ui_theme_alpha_sunset_glow[2];

extern const ui_theme_variable_t _ui_theme_color_pale_spring[2];
extern const ui_theme_variable_t _ui_theme_alpha_pale_spring[2];

extern const uint32_t * ui_theme_colors[2];
extern const uint8_t * ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
