// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SmartWatch_ui

#ifndef _SMARTWATCH_UI_UI_H
#define _SMARTWATCH_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void disappear_Animation(lv_obj_t * TargetObject, int delay);
void appear_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_MainView
void ui_MainView_screen_init(void);
void ui_event_MainView(lv_event_t * e);
extern lv_obj_t * ui_MainView;
extern lv_obj_t * ui_topContainer;
extern lv_obj_t * ui_dayLabel;
extern lv_obj_t * ui_monthLabel;
extern lv_obj_t * ui_midContainer;
extern lv_obj_t * ui_batteryBar;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_hourLabel;
extern lv_obj_t * ui_colonLabel;
extern lv_obj_t * ui_minuteLabel;
extern lv_obj_t * ui_BLEIcon;
extern lv_obj_t * ui_bottomContainer;
extern lv_obj_t * ui_dowLabel;
// SCREEN: ui_FitnessActivityView
void ui_FitnessActivityView_screen_init(void);
void ui_event_FitnessActivityView(lv_event_t * e);
extern lv_obj_t * ui_FitnessActivityView;
extern lv_obj_t * ui_stepsStrLabel;
extern lv_obj_t * ui_stepsLabel;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_BLEIcon);    // assets/BLE_icon_orginal (1).png
LV_IMG_DECLARE(ui_img_preview_png);    // assets/Preview.png


LV_FONT_DECLARE(ui_font_QuantifyFont_16);
LV_FONT_DECLARE(ui_font_QuantifyFont_70);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
